### PR TITLE
Add missing pools Feb 3rd

### PR DESCRIPTION
**Pull request by chainergar**
Add missing pools Feb 3rd

### CODE REVIEW

**Review by silagepete — CHANGES_REQUESTED** [review]
Balances table should only include addresses of underlying assets, like DAI, wBTC, ESD, GUSD, that appear in `console.table(sdk.api.util.tokenList()` and have a price provided by Coingecko. It should not include vault or LP token addresses.

Uniswap and Sushiswap pools should use `getUniswapUnderlying` and should allocate the pool balances to the correct underlying assets in the pool. The 1inch pools might need a change to `getUniswapUnderlying` to calculate the ETH balance in those pools.

**Comment by chainergar** [comment]
I was using getUniswapUnderlying for the uniswap and shushiswap, 1inch swap pools, and get independent token balances for the pools, but all of the blanaces of independent tokens returned 0, I also checked those balances by etherscan readcontract, but they also returned 0 for the balaceOf functions.
So I updated them to get balances from the Vault and LP contracts.
Can you tell me why does it return balance zero?
And I also compare the balances I got from the current progress to the harvest finance dashboard values, and it seems to be matched.
So I decided not to use the UniswapUnderlying.

**Comment by silagepete** [comment]
DeFi Pulse calculates TVL by multiplying the USD value of supported assets by the balance of these assets in the project's contracts. The job of the adapter code is to determine the balance of the supported assets in each vault. The `getUniswapUnderlying` returns the balance of tokens in an LP position so that they can be included in the totals.

Your code calculates and reports the balance of the LP tokens in the vaults. These LP tokens aren't supported and won't contribute to calculated TVL.

The 1inch pools use ETH directly instead of WETH like Uniswap and Sushiswap. When ETH is `token1`, the contract returns the address `0x0000000000000000000000000000000000000000` which isn't a real token address. `getUniswapUnderlying` needs to be extended to handle this.

Most Curve pool LP tokens are not supported tokens. We report an estimate for Curve LP vaults by assuming that the LP vault token price is approximately the price of the least stable supported token in the pool. This could be improved by creating a `getCurveUnderlying` function to get the actual underlying token values.

**Comment by chainergar** [comment]
@silagepete thanks for the comment
As I commented above, formerly I used getUniswapUnderlying function to get the balances, but it returns 0 for all the pairs. I also checked the contract's balances by etherscan, it also returns zero. So if we update like this, we don't get any update on TVL. That's why I didn't use this function. 
If you really still think we have to use getUniswapUnderlying for those pairs which returns zero, can you please take a little look for it why it returns 0? it won't  take much time.
And I used WETH for all the pairs, nothing is using ETH for the tokens, so we don't have this issue.

**Pull request merged**
