### PR TITLE
Move adapter updates from rates-prod to master

### PR DESCRIPTION
**Pull request by arman37**

### CODE REVIEW

**Review by AndreMiras — APPROVED** [review]
Thank Arman for the effort :muscle: 
Very hard to tell with giant PRs, but we know the context of this one, so I'd say let's bite the bullet and move forward.
I haven't yet ran the adapter project locally, but that could be nice if @nedodn or @xcellsior could checkout the branch and give it a try see if that runs OK

**Comment by ruffrey** [comment]
Definitely - thanks for taking this on, @arman37 .

I notice `xtoken` changes here are reverted. We'll need the master version of `projects/xtoken/index.js`

**Review by xcellsior — APPROVED** [review]

**Comment by xcellsior** [comment]
What happened to idex adapter?

**Comment by arman37** [comment]
> 

Reverted `xtoken` changes.

**Comment by arman37** [comment]
> 
what about idex adapter?

**Comment by xcellsior** [comment]
Nevermind on idex adapter. I see what happened, we reverted to using TVL adapter instead of json

**Pull request merged**
